### ISSUE TITLE
An example of true `protected` with decorators?

### ISSUE THREAD

**Issue by trusktr** [tc39/proposal-class-fields#223] opened 2019-02-02 22:02 UTC
The one in `DECORATORS.md` is as plain as `public`. Is there a better way?

**Comment by ljharb** [comment] 2019-02-02 22:07
How would you suggest making a JS value available to an object in a different scope/module, while denying it to every other scope/module, while also continuing to permit further subclassing, and without introducing a circular dependency?

(Absent that feature, imo JS can't really have "protected", because access is binary - either something is reachable/observable/public, or it's unreachable/unobservable/private. I'd love to hear your thoughts tho!)

**Comment by devsnek** [comment] 2019-02-04 15:09
protected makes absolutely no sense in prototypal inheritance, and you bring up the reasons why yourself.

**Comment by rdking** [comment] 2019-02-04 17:14
Figured it out....

@devsnek 
I understand your opinion. Please recognize that it is only an opinion, and not everyone shares it.

@trusktr 
`this.__proto__.constructor` is only an issue for your lowclass implementation. I've created no less than 7 different approaches that don't suffer from that problem. No matter what, however, ES is always just 1 feature short of making it work properly using an ergonomic syntax.

@ljharb 
In case you haven't seen it yet, I finally have an answer for your question. @nicolo-ribaudo did the work of [coding the example](https://github.com/tc39/ecma262/issues/1341#issuecomment-460324083).

**Comment by devsnek** [comment] 2019-02-04 17:34
@rdking what I mean is that, like ljharb and truskatr have said, you need a new state system outside the prototype chain for protected, so by definition, *not by opinion*, protected doesn't fit into prototypal inheritance.

**Comment by rdking** [comment] 2019-02-04 17:53
@devsnek Thanks for the clarification, but it's wrong. There are several approaches that would do the job without requiring "a new state system outside the prototype chain", or at least, without doing anything much different than already being done to implement private fields. If I decided to be overly pragmatic about it, I would say that private fields, or fields in general have the same issue. The only thing required to make protected work is that every subclass use an accessor property that retrieves the value from the owning class. That's not a new state system.

**Comment by ljharb** [comment] 2019-02-04 18:37
I still don’t think I’ve seen an example of a base class, that has a “protected” member, that only subclasses can access, that can be subclassed at any point in the future, that doesn’t require subclasses to share a scope or module, and that doesn’t allow me to see protected members of a sibling subclass by crafting a malicious subclass.

Do you have such an example?

**Comment by rdking** [comment] 2019-02-04 19:56
@ljharb Do you want something that will work in ES today?

**Comment by ljharb** [comment] 2019-02-04 20:01
@rdking i suspect that'd be impossible; if so, I'd be interested to see it - but even as a proposal that requires a language change, I'd be interested to see it written up.

**Comment by littledan** [comment] 2019-02-05 05:22
This issue is a request for decorators, and out of scope for this repository, so closing.

**Closed by littledan** 2019-02-05 05:22 UTC

**Comment by rdking** [comment] 2019-02-05 07:13
@ljharb Take a look at [this](https://stackblitz.com/edit/js-dhethl?file=index.js). It's not decorators, not private fields, and the syntax is in dire need of sugar, but it provides protected in a way that can't be easily leaked.

**Comment by ljharb** [comment] 2019-02-05 07:32
@rdking that was a fun few minutes https://stackblitz.com/edit/js-wqp2mg let's discuss this somewhere else tho, it's not really appropriate for this proposal's repo. Feel free to find me on IRC, or to ping me in a repo for a proposal of your own.

**Comment by rdking** [comment] 2019-02-05 14:31
Nice work. Not quite right though, but I'll try to catch you on IRC to explain the flaw.

**Comment by trusktr** [comment] 2019-03-25 18:02
IRC is too ephemeral, I stopped using it because it's a hassle.

> it provides protected in a way that can't be easily leaked.
> Nice work. Not quite right though, but I'll try to catch you on IRC to explain the flaw.

Can you explain those here?

**Comment by rdking** [comment] 2019-03-26 02:07
@trusktr His `Thief` was a subclass of `Derived`. It's kinda hard to steal the inheritance being handed to you. After the IRC conversation, this was the [final solution](https://stackblitz.com/edit/js-dhethl). It still needs thorough testing to prove it's air tight, but you'll be hard pressed to find a leak.

**Comment by trusktr** [comment] 2019-03-26 06:12
If anyone can find a leak, it's Gus (@devsnek)!

Gus, do you see any way for public code in the previous link gain access to the protected members?

**Comment by devsnek** [comment] 2019-03-26 13:36
I don't really feel like going through that but I can offer the following: If the code uses the prototypal inheritance of the classes to create protected data, it will be accessible in some way, as that's obscurity not security. If it creates a new chain of inheritance, it may very well be properly encapsulated, but then you have the issue of a new hidden chain of inheritance which is rather un-javascript-y, and I would argue your solution belongs in userland, not the language.

**Comment by rdking** [comment] 2019-03-26 14:03
@devsnek It uses neither. Derived classes are given an accessor property with a "private name" that connects back to the original data. This way, while sibling instances all know the same name for a protected field, base, derived, and sibling classes each have a unique name for the protected fields. This keeps one class from spilling the beans about another.

**Comment by devsnek** [comment] 2019-03-26 14:05
that seems to fall pretty squarely under "not prototypal inheritance"

**Comment by rdking** [comment] 2019-03-26 14:07
and yet it's perfectly javascript-y. 😄 
It's not an inheritance chain of any kind. The accessor links directly back to the original data. No hops in between.

**Comment by rdking** [comment] 2019-03-26 14:16
It's a technique I would implement using decorators if the current stage 2 proposal hadn't been shot down for performance issues. I can't do it in Babel since there still doesn't seem to be compatibility between decorators and private fields. Compound this with the problem that decorator-added private fields don't participate in the lexical private name pool for a class. I tried to do it and learned very quickly how short decorators fall from the required goal.

Then to add insult to injury, the new built-in proposal @littledan is working on has even less power. So I can't even get close enough to implement a rudimentary "protected" decorator.

**Comment by trusktr** [comment] 2019-03-29 06:35
> If it creates a new chain of inheritance, it may very well be properly encapsulated, but then you have the issue of a new hidden chain of inheritance which is rather un-javascript-y, and I would argue your solution belongs in userland, not the language.

Why would you argue that @devsnek?

Firstly, I'd consider anything implemented in JavaScript to be... JavaScripty. So if the engine implements it, does it then become non-JavaScripty?

These solutions that we've presented implemented in JavaScript are... implemented in JavaScript.

There's other things we can do at the engine level that is impossible in JavaScript. I do believe that the engine can store protected members on a prototype (f.e. [access mode](https://github.com/tc39/proposal-class-fields/issues/195) is just one idea and there must be more). The engine could decide to mark prototype objects created from `class` syntax as special, in the sense that only those type of objects can have protected or private members, and then perform lookups only when position or lexical scope matches criteria that allows code in that scope to read the variables.

Honestly it isn't hard to imagine, it is only hard to _implement in JavaScript_.

Maybe we should stop limiting ourselves by forking V8 (or similar) and making example language features on the engine side.

**Comment by devsnek** [comment] 2019-03-29 11:58
I say "un-javascript-y" meaning that it doesn't mesh well with the existing design of js. in JavaScript if you change the prototype of some object, that object is now an instance of that. the prototype itself is the source of truth.

the issue people are having is that you can't add protected state to something that uses that system of inheritance. you need to add a new system.

you can start adding lexical position checks and whatnot but then, if I add a function to an object, that function is part of that object, except it can't access the protected state.

re: forking V8, the issue isn't that people don't think this is possible, it's that people don't think it's a good design.

p.s. just so you're aware, i'm going to be muting this issue now.

**Comment by rdking** [comment] 2019-03-29 14:53
@devsnek It's a shame you won't see this.
> the prototype itself is the source of truth.

You have no idea how happy I am to hear you say that. I've argued with several TC39 members and other interested parties who back this proposal over that very concept. Somehow, they have it in their head that a "class" is more about the "constructor" than the "prototype".  I've tried time and again to get through to them that a "class" is a factory that produces instances of a template. In ES, that template (although dynamic) is the prototype.

> the issue people are having is that you can't add protected state to something that uses that system of inheritance.

Actually, you can. The first counter-proposal for class-fields that I presented did exactly that.

**Comment by trusktr** [comment] 2019-04-03 07:01
> if I add a function to an object, that function is part of that object, except it can't access the protected state.

@devsnek That's perfectly fine because that function is (can be) considered to be added from public scope, so it shouldn't gain access.

Syntax aside (imagine your favorite of many possibilities), the following **is** JavaScripty:

```js
export const o = {
  set n(val) {
    protected.n = val * 2
  },
  get n() { return protected.n },
}
```

```js
import {o} from './o'

o.n = 2
console.log(o.n) // 4
```

There's much to desire from this proposal.

**Comment by trusktr** [comment] 2019-04-15 20:22
> If the code uses the prototypal inheritance of the classes to create protected data, it will be accessible in some way, as that's obscurity not security.

Not true, because if the engine is using scope checking to determine whether a public or protected (or private) field is returned (with whatever syntax is chosen for this), then there's nothing to be accessible in the wrong way.

Side question: what problems would arise if we made prototypes of object constructed from `class`es be permanent?

**Comment by rdking** [comment] 2019-04-16 16:16
In some loose fashion, you just described how almost every implementation of Class.js (including the 4.0 version I'm working on now) works. This is also why I have no issues with lexical scope. As long as the environment record of the running function knows which class the function came from, access restrictions can be guaranteed. Protected inheritance then just becomes an accessor to a class-uniquely named accessor to the original property as defined by the owning class. The double accessor approach ensures that sibling classes cannot leak each other's protected data since they don't know the name of the intervening accessor.

**Comment by trusktr** [comment] 2019-07-08 21:28
@rdking A Sweet.js macro that would transpile a regular ES class to Class.js (showing true protected and privates) would be nice! I've also been pondering about making a transform for TypeScript so that `private` gives true privacy in the JS output.

**Comment by rdking** [comment] 2019-07-08 23:23
What I'm working on will support classes that look like this:

```js
class Ex extends Foo {
   private a;
   private b = init;
   private c() {...}
   protected d;
   protected e = init;
   protected f() {...}
   public g;
   public h = init;
   public i() {...}
   //These 3 are also public for compatibility sake with ES6 classes
   j;
   k = init;
   l() {}
   // Yes, accessors can have different privileges on them
   private static set m(v) {...}
   protected static get *m() {...}
   public async n() {...}
}
```
... and it will all compile down to ES2017 compatible code. The class itself will be an ES5-style class with access to the enhancements brought about in later versions of ES. I've almost got it worked out. I'll publish the repo for it when it's working.

**Comment by trusktr** [comment] 2020-01-02 23:58
@rdking Cool. Any progress on the above?
