### ISSUE TITLE
The '#' looks awful, please change it 

### ISSUE THREAD

**Issue by gynet** [tc39/proposal-class-fields#99] opened 2018-05-06 23:38 UTC
The '#' looks really awful and even hard to read!

**Comment by gynet** [comment] 2018-05-06 23:41
Not only best taste, I think many developers wont like writing such code
```JavaScript
 this.#x++;
```
Please justify or consider to chose something prefered by the community!

**Comment by jkrems** [comment] 2018-05-06 23:45
> Please justify

There's a long FAQ that is justifying the choice in case you missed it: https://github.com/tc39/proposal-class-fields/blob/master/PRIVATE_SYNTAX_FAQ.md :)

**Comment by littledan** [comment] 2018-05-08 23:13
Closing as a duplicate of several other issues.

**Closed by littledan** 2018-05-08 23:13 UTC
